project:
  type: book
  output-dir: docs
  resources: 
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"
    
    
book:
  title: "Thermal Ecology in R"
  author: "Nicholas Wu"
  date: today
  date-format: Do MMM YYYY
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://nicholaswunz.github.io/thermal_ecology_R/
  repo-url: https://github.com/nicholaswunz/thermal_ecology_R
  sidebar: 
    logo: https://raw.githubusercontent.com/nicholaswunz/thermal_ecology_R/e38e0b4da3cda8ecb6d098d216a06fb3d2a8514c/images/tea-logo.svg
  page-footer:
    border: true
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>. This work is licensed under a [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/)
  
  chapters:
    - index.qmd
    - part: "Environmental Data"
      chapters:
      - intro.qmd
      - summary.qmd
    - part: "Physiological Data"
      chapters:
      - phys_respirometry.qmd
      #- summary.qmd
    - part: "Behavioural Data"
      chapters:
      - behav_torpor.qmd
      #- summary.qmd
    - part: "Comparative Data"
      #chapters:
      #- intro.qmd
      #- summary.qmd
    - part: "Simulation"
      #chapters:
      #- intro.qmd
      #- summary.qmd
appendices:
    - references.qmd

bibliography: ./bib/references.bib
csl: ./bib/the-journal-of-experimental-biology.csl
link-citations: true

format:
  html:
    grid:
      body-width: 900px
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    include-in-header: _fathom.html
    theme: 
      - theme.css
      - theme.scss
      - lumen
      
fontsize: 98%;

execute:
  code-annotations: hover
  number-depth: 3

