# Welcome {.unnumbered}

```{r}
#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(lubridate)
library(stringr)

```

This book is a practical guide for anyone working with thermal ecological data 
using R. It focuses specifically on the processes and challenges you'll face with 
such data, and provides best practices for reporting.

The intended audience is for graduate students new to thermal ecology and experts
in the field who are unfamiliar with R. This book will mainly follow the [`tidyverse`](https://style.tidyverse.org/) 
syntax for consistency in learning experience. 

If you are new with R and not use basis data manipulation and coding, I have a 
series of [tutorials](https://nicholaswu.quarto.pub/ecs200/) for undergraduate 
students working with ecological data. Most relevant for this audience is week 
1–4 contents (quality check, tidy data, diversity indices, and descriptive stats).

The tutorials teach you how to check for the quality of the raw data you imported, 
the steps to correct errors in the raw data, how transform raw data to something 
usable for analysis, and get familiar with clean code.

## Environmental Data

Learn how to load and clean raw data from own data loggers, access climate 
databases and microclimate simulations, and calculating metrics of heatwaves.

- Data loggers (to do)
- Online climatology data (to do)
- Online microclimate data (to do)
- Detecting heatwaves/cold spells with `heatwaveR` (to do)

## Physiological Data

- Thermal performance curves (to do)
- [Respirometry](phys_respirometry.qmd) (10% complete)
- Thermal-death-time curves (to do)
- Q10s and rates of change (to do)

## Behavioural Data

- Torpor/arousal patterns (to do)
- Thermal images (to do)
- Thermoregulation (to do)

## Comparative Data

- Effect sizes (to do)
- Comparative analysis (to do)
- Scaling relationships (to do)

## Simulation

- Operative temperature models (to do)
- Dynamic Energy Budget (to do)

## Other

- Repeatability (to do)


### Acknowledgements

This book was inspired by the [Cleaning Biodiversity Data in R](https://cleaning-data-r.ala.org.au/) book. 
This book is a collaborative effort by members of the [Thermal Ecology Alliance](https://www.thermalecologyalliance.org/).

